# -*- coding: utf-8 -*-
"""MRUniqueWordCount

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11eTygb7OatvJzRHte5warjJqqqBKUyIV
"""

!pip install mrjob

from mrjob.job import MRJob
import re

line = 'Hello. How are you? I hope you are good!'
WORD_REGEXP = re.compile(r"[\w']+")

def mapper_reducer():
    freq = {}
    for word in WORD_REGEXP.findall(line):
      if word in freq:
        freq[word] += 1
      else:
        freq[word] = 1

    unique_words = [word for word,count in freq.items() if count==1]
    print(unique_words)
    print('The count of unique words is:',len(unique_words))

if __name__ == '__main__':
  mapper_reducer()