# -*- coding: utf-8 -*-
"""load balancing assignment 4 final code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gOS6yQ7O_SIGZed0b7gEEL0pvM81YHYQ
"""

import random

class Server:
    def __init__(self, name):
        self.name = name
        self.connections = 0

class LoadBalancer:
    def __init__(self, servers):
        self.servers = servers

    def round_robin(self):
        server_index = 0
        while True:
            yield self.servers[server_index]
            server_index = (server_index + 1) % len(self.servers)

    def random_selection(self):
        while True:
            yield random.choice(self.servers)

    def least_connection(self):
        while True:
            min_connections = min(self.servers, key=lambda x: x.connections)
            min_connections.connections += 1
            yield min_connections

def simulate_requests(load_balancer, num_requests):
    print("Simulating {} requests...\n".format(num_requests))
    for i in range(num_requests):
        server = next(load_balancer)
        print("Request {} handled by Server {}".format(i+1, server.name))
    print("\nSimulation complete.")

if __name__ == "__main__":
    server1 = Server("S1")
    server2 = Server("S2")
    server3 = Server("S3")
    servers = [server1, server2, server3]

    lb = LoadBalancer(servers)
    ch=int(input('1. Round Robin        2. Random         3.least       Enter : '))
    if ch==1:
        load_balancer = lb.round_robin()
        simulate_requests(load_balancer, 10)
    elif ch==2:
        load_balancer = lb.random_selection()
        simulate_requests(load_balancer, 10)
    elif ch==3:
        load_balancer = lb.least_connection()
        simulate_requests(load_balancer, 10)
    else:
        print("wrong choice")